### ISSUE TITLE
Uninstall cleanup

### ISSUE THREAD

**Issue by ed-cooper** [WorldLanguages/isOnlinev2#12]
https://developer.chrome.com/extensions/runtime#method-setUninstallURL

I'll implement a server side page to delete isonline users, preventing any issues with "last online 3 months ago"

To consider: How can we tell between a user being genuinely deleted and a bot just spamming that URL to delete every account?

**Comment by joker314** [comment]
Can't you add the key to the URL?

**Comment by joker314** [comment]
it's a function after all.. not a constant

**Comment by ed-cooper** [comment]
Yep, that works
I'll get working on it at some point in the future

**Comment by ed-cooper** [comment]
Uninstall page will be `isonline/api/v1/[username]/[key]/delete`

**Comment by JordanB-1337** [comment]
but what is going to happen if their scratch account is delted, not just isonline

**Comment by ed-cooper** [comment]
Then nobody will be able to access their profile so it shouldn't be an issue (and worse case scenario they just show as offline)

Having unused accounts on the server isn't a big issue (as long as used accounts outnumber the unused ones) This is more about stopping someone being displayed as offline, when they are online but have simply uninstalled isonline

**Comment by joker314** [comment]
How about if you have been offline for 6 months, you have to re-key? that would help free up some server space no?

**Comment by ed-cooper** [comment]
Server space is not an issue

**Comment by ed-cooper** [comment]
Uninstall page is now available:
`https://scratchtools.tk/isonline/uninstall/?user=[username]&key=[apikey]`

Just needs implementing into extension now

**Comment by WorldLanguages** [comment]
Implemented
