### ISSUE TITLE
Multiple extension installs for the same Chrome account

### ISSUE THREAD

**Issue by benajaero** [WorldLanguages/isOnlinev2#18]
In Chrome, users are able to create an account. If they sign into any other Chrome browser then all their extensions and bookmark are re-downloaded. The problem here is that when I sign into Chrome on a different laptop, I have to reinitialize isOnlinev2. isOnlinev2 has to be setup each time and only works for one browser.

**Comment by WorldLanguages** [comment]
isOnline v1.3 will use chrome sync, but the current version doesn't
