### ISSUE TITLE
Notifications for new messages

### ISSUE THREAD

**Issue by lholliger** [WorldLanguages/isOnlinev2#19]
This would help users that have chrome launched be notified if they have a new message on scratch, the code has a few bugs, but could be fixed when implemented if it would be.

I wrote an extension that notifies the user if there is a new notification on their profile, below is the code used by the extension:
```
function httpGet(theUrl)
{
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.open( "GET", theUrl, false ); // false for synchronous request
    xmlHttp.send( null );
    return xmlHttp.responseText;
}

var username = "DatOneLefty"; // change for your user
var polltime = 10;           // how often to check servers (in seconds)


chrome.notifications.onClicked.addListener(function() {   chrome.tabs.create({ url: "https://scratch.mit.edu/messages"}); });
var current = httpGet("https://api.scratch.mit.edu/users/" + username + "/messages/count");
var cache = current;
console.log(cache);

var options = {
    type: "basic",
    iconUrl: "https://scratch.mit.edu/favicon.ico",
    message: ("New message, total: " + cache),
    title: "ScratchNotifier"
}
chrome.notifications.create(null, options);

setInterval(function() {
  current = httpGet("https://api.scratch.mit.edu/users/" + username + "/messages/count");
  if (cache < current) {
    cache = current;
    var options = {
        type: "basic",
        iconUrl: "icon.png",
        message: ("New message, total: " + cache),
        title: "isOnline"
    }
    chrome.notifications.create(null, options);
    }
  console.log(current);
}, (polltime * 1000));

```
The issues in this code:
the username is not dynamic
it shows `{"count":0}` instead of just `0`

**Comment by andybrwr** [comment]
do you have this on github somewhere

**Comment by lholliger** [comment]
nope, ill post it if you want it

**Comment by andybrwr** [comment]
yes please :P i want to fix the stuffs xD

**Comment by andybrwr** [comment]
btw do i have to allow it to send notifications or will it just work? me nu chrome lots more time recent

dat perfect grammar.

**Comment by lholliger** [comment]
i dont remember, ill post it as a gist
https://gist.github.com/DatOneLefty/87a26ec73361d3b5090995ad44b05971

**Comment by csf30816** [comment]
@DatOneLefty Why don't they just install my Scratch Messages Android App?

**Comment by andybrwr** [comment]
dont have android
also you know it would be nice to have a chrome extension so yeah

**Comment by WorldLanguages** [comment]
After this update we'll work on a Scratch extension with lots of tools, that are outside the scope of isOnline. :D

**Comment by lholliger** [comment]
@WorldLanguages instead of making your own you might want to look at Furball, it has many tools that improve scratch and keeping them in one place would be better than having multiple extensions
