### ISSUE TITLE
Update me

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnlinev2#22]
What's up? How are things moving along? What things are we planning on implementing?

**Comment by Torotv** [comment]
Helllo.

**Comment by WorldLanguages** [comment]
Hey! I'm saturated in homework stuff at the moment, and I need a clean mind to actually code :P 

I'll make a change to the shift+enter code and then I'd release it.

**Comment by WorldLanguages** [comment]
Should I take care of translations now?

**Comment by joker314** [comment]
I'm happy to continue with it.. there's nothing new right? Remember to credit those mentioned in the Discord!

**Comment by WorldLanguages** [comment]
Nothing new

Things to do:
Check all strings are in all languages
Add translation credits (every messages.json should have at the end a credit term, if not, check in Spanish and copy paste)

Busy is killing m e :(

**Comment by joker314** [comment]
Okay, have we made the timings consistent (3 vs 5 mins)?
