### ISSUE TITLE
Halloween easter egg, maybe?

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnlinev2#24]
Scratch is a wonderful resource inspiring young children to educate themselves about the computers they constantly use; providing them a tool to express themselves in a way that teaches concepts of programming -- and creating a relaxing environment through social aspects of its site. And then there's us. We provide a service for that social aspect, when we could be helping Scratch to reach out to the young people of the world and showing them how to code.

Because, let's face it, not everybody uses Scratch for programming. And that's fine. But if we can show a few more people how to code -- perhaps in a text-based language we create ourselves -- then it's all worth it, isn't it?

So, how do we do this without losing the fun aspect that with which isOnline prides itself? Well, on Halloween, we could create a fun new message box -- the jack-o-lantern box -- which will hold all the automated notifications from Dr. Halloween-Monster, who will guide the child through their experience of the day.

It will look like this in the navigation bar

![image](https://user-images.githubusercontent.com/18113170/31865408-8e4a23ac-b766-11e7-818a-159c408cd2f2.png)

It's first message will be

> Ho ho ho! Wait, it's Halloween, not Christmas... whoops! Mwahahahahaha.. that's better. I'm Dr. Halloween-Monster, and I'd love to help you learn to code in a fun and creative way? At the end, I'll give you a special code that will make your profile have a picture of me (🎃) next to your username, and I'm sure you'll get a lot out of it. So, are you with me? _Yes_ / _No_

Once the user presses "Yes", the child gets another notification. It will read

> Yay! I'm so excited to work with you **@username**. Okay, so when you're a pumpkin like myself, you get invited to work for the isOnline team. I have to run around and sit on everybody's navigation bar for a *whole day*. It's exhausting. But, while working for the isOnline team, I've learnt a lot about coding, and how fun it is! Can we play a game?
>
> When I type
> ```
> move 5 steps
> ```
>
> I can get halfway to my favourite candle. Can you help me get all the way there? That would be so awesome if you could!
> ![image](https://user-images.githubusercontent.com/18113170/31865687-9d631ca0-b76a-11e7-86e7-73cada832dd9.png)
>
> ```
> > type your code here
> ```

The user will type `move 10 steps` and then they get yet another notification! It will teach the user about variables

> Ah, that was nice and warm... for a while.  The Evil Duchess of Halloween stole my candle. She's so mean. However, Count Halloween has been a huge help, they managed to get the candle but they dropped it when the Duchess caught up with them. She snatched it off them and it fell to the ground. Count Halloween was so distraught that they couldn't've done more, but don't worry -- you can help us, right? I have no idea where the candle is, but the Count says that it was *`x`* meters away from me when they snatched it from the Evil Duchess, and then she made them drop it *half-way* back.
>
> Can you help me figure out which command I should use to get back to get my candle?
> ```
> move x steps
> ```
> will make me go to where the Count intercepted the Duchess, and
> ```
> move 10 / 2 steps
> ```
> will make me go 5 meters. That's because `/` is *division*, and 10 *divided by* 2 is 5. So, can you help me find my candle?
> ```
> > type your code here
> ```

etc. etc. etc.

So, do you like the idea? We can always do this next halloween if time is the issue; but we definitely need this translated into many languages.

**Comment by WorldLanguages** [comment]
Seems very fun!!!

However I don't think this is worth being translated. Would you translate something that will only appear for a day?

**Comment by WorldLanguages** [comment]
(btw, I added an easter egg to the popup - have at least one online friend and do the konami code :P)

**Comment by joker314** [comment]
Woah that's a cool easter egg.

I see what you mean, but this is our opportunity to educate our kids about code. It seems a bit unfair to deny you that experience just because you don't speak English -- even though I get it, it's a lot of effort.

**Comment by joker314** [comment]
Pssst ask Chooper (is he still doing it?) to add a donate button?

**Comment by WorldLanguages** [comment]
Yes I see how it is unfair - but I don't like to abuse of translators. They offer their work so other people can use the extension in their language, not to translate easter eggs that aren't necessary to implement (but that may be helpful).

We can get this localized, but we have to tell the translators that this is for an easter egg and it's optional for them to translate this (well, it's always optional, but you get what i mean)

**Comment by joker314** [comment]
Yeah, I think it might help if we delay this for next halloween and give them time to translate a bit at a time?

_Or, we could pay some translators if we add a donate button_

**Comment by WorldLanguages** [comment]
Why not do it this year and repeat it next but localized

**Comment by joker314** [comment]
Hmm yeah sure, let's see if we can program this thing in time!

**Comment by WorldLanguages** [comment]
What if we do this for santa but in christmas :P

**Comment by joker314** [comment]
Yeah, that might work~ though we have to be careful not to pick sides with religions :P

**Comment by joker314** [comment]
https://scratch.mit.edu/users/DrHalloweenMonster/ - This is what I'm doing instead of coding :(

**Comment by joker314** [comment]
Woah people stalk this repository -- DrHalloweenMonster already has 2 followers!

**Comment by joker314** [comment]
AAaaaah done

**Comment by MasterOfTheTiger** [comment]
This sounds great! I hope this idea works out. :)

**Comment by DeleteThisAcount** [comment]
i need to update isonline NOWWW

**Comment by joker314** [comment]
> ```
> Hi, I'm jokebookservice1 -- a developer for isOnline.
> 
> I'm really excited to tell you about our newest recruit, Dr Halloween-Monster! He has a part-time job sitting on your navigation bar on Halloween! He's only up for one day, but he's very busy!
> 
> Just head over to [url=https://scratch.mit.edu/io-halloween-messages]your halloween inbox[/url] and click on the link you get. You'll be faced with challenges that will require you to code in a Scratch-like language.
> 
> It's quite simple, with only two challenges, but we hope that on future days we'll have more advanced challenge where we'll have a chance to develop the characters a bit more.
> 
> And, if you get to the end, you can put a picture of Dr. Halloween-Maker next to your username on your profile!
> 
> [img]http://i.cubeupload.com/lBMXJB.png[/img]
> 
> So, let's meet the team -- shall we?
> 
> [list]
> [*] [i]Dr Halloween-Monster[/i] is an innocent pumpkin just trying to get his candle.
> 
> [*] [i]the Evil Duchess of Halloween[/i] is a thief who takes Dr Halloween-Monster's candle without permission. She's not very nice.
> 
> [*] [i]Count Halloween[/i] is Dr Halloween-Monster's best friend. They can fly -- just like the Duchess, but they use their power for good; unlike the Duchess who uses it for nothing but evil, meaning that they take back the candle and return it to Dr Halloween-Monster.
> [/list]
> 
> They all have Scratch accounts too! [url=https://scratch.mit.edu/users/DrHalloweenMonster/][i]Dr Halloween-Monster[/i][/url] | [url=https://scratch.mit.edu/users/DuchessOfHalloween/][i]the Evil Duchess of Halloween[/i][/url] | [url=https://scratch.mit.edu/users/CountHalloween/][i]Count Halloween[/i][/url]
> 
> Now, I was actually quite good friends with Dr Halloween-Monster before I hired him, but he didn't confide with me his problem with the Duchess until he joined the team. And then I realised what was staring me in the face -- [i]you[/i]! Count Halloween is trying their best, but not even the bravery of Dr Halloween-Monster and the Count quite outwits the Duchess.
> 
> But we know that you can help us! We think you have the abilities that'll help get the candle back.
> 
> [big]If you're not that interested in coding, we're also hosting an [b]art competition[/b]![/big]
> 
> It's true! After all, coding is being creative -- and you can't make a cool app if you don't do any drawing.
> 
> So, how do you participate? Well, just post a drawing (or photo!) of what you think Count Halloween, the Evil Duchess of Halloween, or Dr Halloween-Monster look like.
> 
> If you do take the time to enter, we'll be sure to let you know what we like about it.
> 
> Rules:
> 
> [list]
> [*] Be creative!
> [*] Be nice
> [*] Give credit where credit is due
> [/list]
> 
> That's it! Once you've submitted an entry of how you interpret one of the three characters, you get a special code that only works for you, that'll give you a paintbrush badge next to your username.
> 
> [img]http://i.cubeupload.com/jL4grb.png[/img]
> 
> You can combine your badges if you want.
> 
> [img]http://i.cubeupload.com/kOYhbL.png[/img]
> 
> Oh, and if the character you draw really likes the art you've made they might just give you a quick follow ;)
> ```

This issue-comment is licenced under a Creative Commons Share-Alike 2.0 licence in order to permit me posting it on the Scratch forums.

**Comment by joker314** [comment]
This seems like it's done
