### ISSUE TITLE
Who do we credit

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnlinev2#28]
This is important for the update blog.

# Translations

## Vietnamese

- [X] Translate old words
- [X] Translate new words

Credits

- EvanKTC

## French

- [X] Translate old words
- [x] Translate new words

**Progress of new words, 5 / 6**

Credits

- Nobelix _(everything)_

## Spanish

- [x] Translate old words
- [x] Translate new words

Credits

- World_Languages _(everything)_

# Help

Thanks to DeleteThisAcount for helping to develop and beta test.

Thanks to RedMango22 for reporting a bug

Thanks to the current isOnline team for developing the extension.

**Comment by DeleteThisAcount** [comment]
Yay I'm there!!! oh wait you spelled acount correctly :( It's acount not account :P

**Comment by joker314** [comment]
Oh no! I spelled something correctly!

**Comment by DeleteThisAcount** [comment]
big problem :P

**Comment by DeleteThisAcount** [comment]
:hooray:

**Comment by joker314** [comment]
@WorldLanguages Yay! Make sure to credit everyone :)

**Comment by bob1171** [comment]
Thanks, Drew
