### ISSUE TITLE
Unknown status on Halloween

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnlinev2#30]
Steps to reproduce:

1) Set your computer's time to Halloween
2) Visit my profile
3) Observe that the status is "Unknown"

4) Visit another user's profile
5) Observe the status isn't "Unknown"

**Comment by joker314** [comment]
Thanks to RedMango22 for the report.

**Comment by joker314** [comment]
I removed the special codes from my About Me and WIWO and the bug is still there! Why?

**Comment by joker314** [comment]
Status works on 30th of October

**Comment by joker314** [comment]
And 1st of November. There's some issue with the Halloween code, then?

**Comment by joker314** [comment]
DeleteThisAccount has a similar issue!!!

**Comment by joker314** [comment]
Uuhhh come on guys what do we have in common?

**Comment by joker314** [comment]
We've both used the dev version, and we've both done the Halloween stuff

**Comment by joker314** [comment]
There has to be a reasonable explanation

**Comment by joker314** [comment]
Otherwise we'll have to remove all the Halloween stuff :(

**Comment by joker314** [comment]
We are both reading timestamps from the 23rd of October; that's not good because it's exactly 7 days before Halloween.

**Comment by joker314** [comment]
However, that can't be right... one moment

**Comment by joker314** [comment]
1st of November doesn't work now, hmm. The timestamps seem to be stuck

**Comment by joker314** [comment]
**The extension isn't sending it's requests to update its status for some reason**

**Comment by joker314** [comment]
It stopped sending it on the 23 OCT, when I first made and tested the halloween feature. Further testing will be carried out tomorrow.

**Comment by DeleteThisAcount** [comment]
hmm.... I doubt this will happen on the real halloween

**Comment by joker314** [comment]
The problem is not with the Halloween code; but with switching your date to a date in the future. This sets the timestamp to somewhere in the future.

**Comment by joker314** [comment]
`localStorage.removeItem("iOlastOn")` should fix it

**Comment by WorldLanguages** [comment]
This is just because you're playing with the date I think
