### ISSUE TITLE
Setting date to future causes issues with timestamp stuff

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnlinev2#32]
If you set your timestamp to a date in the future, then go back to the present, `localStorage.iOlastOn` causes issues since it stays in the future and blocks any requests until that date.

**Comment by joker314** [comment]
(see #30)

**Comment by WorldLanguages** [comment]
That's because if currentTimestamp-iOlastOn < 10 no requests are sent. You can edit it to ... < 10 && ... >-1 and this will be fixed. There would still be a tiny issue during 10 seconds, but I wouldn't even consider it a bug because many factors have to give place at the same time

**Comment by joker314** [comment]
I've commited a change, we need to check if the bug still exists
