### ISSUE TITLE
When do we update the forum thread for Halloween

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnlinev2#33]
So, currently, Halloween starts on the *user's* Halloween; but this isn't the same around the world.

Shall we update the thread on, say, the 27th, that way we're guaranteed that everybody will see it but nobody notices early?

**Comment by joker314** [comment]
I'm doing it now

**Comment by DeleteThisAcount** [comment]
You could just... Have is online only show it on their halloween
