### ISSUE TITLE
Firefox doesn't send notifications in the Friend List feature

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnlinev2#35]
In v1.5 we've seperated friend list and notifications; but we need to do more.

Preferably in a non hacky way.

**Comment by WorldLanguages** [comment]
Do more what?

**Comment by joker314** [comment]
We need to make notifications work on firefox

**Comment by WorldLanguages** [comment]
Tracking in #42 - sorry, forgot about this issue
