### ISSUE TITLE
Should "friends" be optional?

### ISSUE THREAD

**Issue by WorldLanguages** [WorldLanguages/isOnlinev2#36]
Now "friends" doesn't require any permission so I'm not sure we have to ask people to enable it? It could be enabled by default or not deactivable

**Comment by DeleteThisAcount** [comment]
I just want to be able to see my friends WITHOUT notifications.

But honestly I dont have any friends. (On my friend list that is :P)

**Comment by joker314** [comment]
People should be able to disable it because of mobile data charges

**Comment by WorldLanguages** [comment]
@joker314 no mobile data charges if there are no friends

**Comment by WorldLanguages** [comment]
Conclusion: No need for it to be optional. I'll make it so it's always enabled now :)

**Comment by WorldLanguages** [comment]
Made optional
