### ISSUE TITLE
i wana be in the trusted dev team?

### ISSUE THREAD

**Issue by DeleteThisAcount** [WorldLanguages/isOnlinev2#40]
Can I join the "Trusted Dev Team" I know I have asked this a few times but you said that you're not looking for devs. Herohamp is in the trusted dev team? I have beta tested a lot. I know about how the extension works and I can answer people on @isOnlinev2 on scratch. I just want to let people know that I have helped here a few times.

**Comment by Sheshank-s** [comment]
I'll let @WorldLanguages answer this one.

**Comment by WorldLanguages** [comment]
Hello @DeleteThisAcount , herohamp is actually joining the dev team.

I don't like the idea of doing a separate role called "trusted" - won't everyone request it?

However I see you deserve creditz so I'll make you the user that posts emojis in the update blog :D

**Comment by DeleteThisAcount** [comment]
Yay!!!!

**Comment by DeleteThisAcount** [comment]
BTW trusted was like next to peoples name on the io scratch account it said like io dev

**Comment by DeleteThisAcount** [comment]
Can't I 'actually' join the dev team tho?

**Comment by WorldLanguages** [comment]
@DeleteThisAcount We aren't adding any more members. Herohamp is an exception, and you'll find why soon.

I don't remember if I told you before we'll start with a MSU like extension, maybe called Scratch+? I'd be glad to have you testing on there :)

**Comment by WorldLanguages** [comment]
testing... and developing too :P

**Comment by WorldLanguages** [comment]
(I'm closing this but we can still talk here)

**Comment by DeleteThisAcount** [comment]
Okeee

**Comment by DeleteThisAcount** [comment]
Can we have customization for profiles!!!!!???
