### ISSUE TITLE
Tell crown users isonline.tk is broken

### ISSUE THREAD

**Issue by WorldLanguages** [WorldLanguages/isOnlinev2#47]
If possible, let them replace isonline.tk with a working link automatically by clicking a button

**Comment by radioblahaj** [comment]
You Should Make the .ga link.

**Comment by Ascor8522** [comment]
Just search in Google which user have put a link to isonline.tk and tell the to change to ison.ga (edited ur typo)

To find all the users with the wrong url their Scratch page, just type in Google:
`
site:scratch.mit.edu/users/ +isonline.tk
`

**Comment by DeleteThisAcount** [comment]
or just check if they have isonline.tk in their about me and tell them to change it

**Comment by Ascor8522** [comment]
## **Noticed users:**
enzocosmos
TrueFBK
ratchetyclank
Dadyno
ohlinator
TheAwesomeGuy16
hellodude1231
cf65rcjurhvj
MysteryHex27
GalaxiaRedwood
arloclc
masonthecoolguy
RememberNovember
Tigy08
UltimateEXEHunter
HarrietNewton
alexixi
lovekitty1
jacob630
Bouboufez
luisbarretto
ma15fo43
ScriptedAwesome
Witherbrine699
MrMinecraftMan404
Austinato
ScratchyCat5100
Alzter
GoldAnimations
RoastedSquirrel64
Funny-People
-Vuton-
RubiksMaster456
marceaupatu123
csf30816
Anais3000
MathPenguinTv
Dobby-Lestrange
Aerdian
Inb4
CD20Superness
myed
GoldenFoxyTheLegend
cbuugdrama9
iamhappy77
MikeShatter
Loomman
-bronze-

**Comment by radioblahaj** [comment]
SO, They Can Use The Link ison.cf?
Where is The source code for the crown?

**Comment by Ascor8522** [comment]
It's in Code.js at lines 509 and 517

**Comment by WorldLanguages** [comment]
Thanks so much @Smrman for all the time you used to do that big list! I honestly can't express how surprised I am because somebody took the time to do that.

Unluckily, we're making this automatic, meaning we don't have to search for crown users. Thanks for your work <3

**Comment by WorldLanguages** [comment]
@DeleteThisAcount We will let them isOnline do that automatically! :)

**Comment by radioblahaj** [comment]
So, No Crown For Users?

**Comment by radioblahaj** [comment]
Thanks!

**Comment by kyleplo** [comment]
Maybe accept the links:
http://ison.ga
http://isonline.cf
http://aremyfriends.online

**Comment by joker314** [comment]
Given that the crown is no longer allowed, I think that reaching out to users should be exclusively to notify them to *remove*, not replace the link.

**Comment by WorldLanguages** [comment]
@joker314 The ST already removed the advertising, and I already removed the code for this, so I'll just close the issue
