### ISSUE TITLE
I'd like to help you...

### ISSUE THREAD

**Issue by Ascor8522** [WorldLanguages/isOnlinev2#53]
Hi,

Just to tell you all I'm intersted in helping you to improve and develop isOnline.
It's already been quite some time since i'm using it and i find it really great.

I have a good knowlege of Javascript, HTML, CSS, C++ (not needed in this case).
I already made an extension for Scratch (it was more an user-script).
It wasn't about adding social function but small functionalities to make the website more confortable to use.

I has a few features, like adding some more emojis, adding buttons tu write in colored text more easyly on the forum, putting the "Discuss" button back on the navbar, etc..

My script is working trough Tampermonkey / Greasemonkey and can be found here : https://github.com/Smrman/Scratch-Forum-UserScript

The link for a quick install (requires TM/GM): https://github.com/Smrman/Scratch-Forum-UserScript/raw/master/Scratch-Forum-UserScript.user.js

Also, I speak multiple languages: English of course, French, Dutch and I understand German and some words of Spanish...

I would be honored to help you.

~
Smrman

**Comment by joker314** [comment]
Thanks for taking the time to write this out.

Feel free to submit pull requests if you'd like to help out!
