### ISSUE TITLE
Isonline Maintained by

### ISSUE THREAD

**Issue by radioblahaj** [WorldLanguages/isOnlinev2#54]
|It Says Isonline is maintined by @GreenBayRules @WorldLanguages @jookbookservice and @choper100
Where Is Herohamp?

I Cou;d Fix This If i could find that in popup.html.
Which Lines is in it?
@DeleteThisAcount

**Comment by Sheshank-s** [comment]
Thanks for the heads up :D I fix this.

**Comment by Sheshank-s** [comment]
Fixed :D
