### ISSUE TITLE
About ST's extension disallowing

### ISSUE THREAD

**Issue by apple502j** [WorldLanguages/isOnlinev2#57]
By it we can't put iO links or ads in our prifile. So:

* Remove crowns and emojis
* Alert for using users

Of cource, I disagree with ST, but this is important to protect the users.

I forked:  apple502j/isOnlinev2
What do you think?

**Comment by radioblahaj** [comment]
Instead; they can make all users have the crown
And you are still allowed to use emojjis

**Comment by Sheshank-s** [comment]
If all users have the crown, what is the point of it? We will be removing the crown.

**Comment by radioblahaj** [comment]
It's good. No! I can help

**Comment by WorldLanguages** [comment]
We'll remove `_isonline_,` other emojis don't necessarily break the policy in my opinion

**Comment by apple502j** [comment]
Okay
