### ISSUE TITLE
Update 1

### ISSUE THREAD

**Issue by WorldLanguages** [WorldLanguages/isOnlinev2#6]
- [ ] Better "away" detection
- [ ] Detect 403 on POST requests
- [ ] Add manual status choosing (Online, Absent, DND, Ghost)

**Comment by joker314** [comment]
Why are all issues being closed? Has all this been implemented?

**Comment by WorldLanguages** [comment]
No, it's just me don't knowing what update actually do next :P

**Comment by joker314** [comment]
Just keep a list open of things people are suggesting, and we will get a few done each update :)
