### ISSUE TITLE
Not really an io issue but

### ISSUE THREAD

**Issue by DeleteThisAcount** [WorldLanguages/isOnlinev2#60]
uhh I can't login to scratch for some reason I won't be able to test stuff on io until I can. I just have my fingers crossed that I'm just forgetting my password and somebody hasn't changed it.

**Comment by DeleteThisAcount** [comment]
Welp I got hacked. I'ma go change my password and stuff.

**Comment by Sheshank-s** [comment]
This shouldn't be here...
