### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by kyleplo** [WorldLanguages/isOnlinev2#63]
These errors appear in the console:
![image](https://user-images.githubusercontent.com/31634240/40445683-d7af5fae-5e9a-11e8-9848-4ea68d45b4db.png)

**Comment by MasterOfTheTiger** [comment]
It must have been disconnected.

**Comment by kyleplo** [comment]
I think the entire scratchtools.pw site is down.

**Comment by kerrtrvs** [comment]
I think @herohamp hosts scratchtools.pw on his server.

**Comment by haylinmoore** [comment]
Its up again, sorre

**Comment by radioblahaj** [comment]
that's sad. Hopefully, Isonline users didn't care and delate the app

**Comment by haylinmoore** [comment]
Welp it is going down for 2 month in a couple of days so, thats the real test

**Comment by MasterOfTheTiger** [comment]
@herohamp Why don't you find a replacement for that time?

**Comment by MasterOfTheTiger** [comment]
@herohamp Where is the code you run. Could someone else not run it?

**Comment by WorldLanguages** [comment]
You've got privacy concerns, we just can't let anyone host this for
thousands of kids

**Comment by Sheshank-s** [comment]
![image](https://user-images.githubusercontent.com/11379161/40571374-647f0a30-604c-11e8-8f27-032cf4e87409.png)
lol
