### ISSUE TITLE
isOnline no longer seems to work

### ISSUE THREAD

**Issue by modernide** [WorldLanguages/isOnlinev2#64]
It says "Loading Status" forever, when you force it to check someones statues, it returns "Error", when i deleted it, http://scratchtools.pw/ returns a 502 error

**Comment by WorldLanguages** [comment]
We will stop hosting it until mid July official announcement soon :)

**Comment by radioblahaj** [comment]
Why?

**Comment by Sheshank-s** [comment]
@Narulacodes Personal Reasons
