### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnlinev2#7]
Here is a list of things that isOnline users are requesting. We should consider each idea, but remember that all ideas must:

* Make sure the community guidlines cannot be broken using it
* Not access or set any personal user data

Now, then, here are the suggestions

- [ ] Manual status selections... "Do not disturb", "Offline (ghost)", "Away", "Normal (online)"
- [ ] Detect if a 403 response is received after POST requests

**Comment by joker314** [comment]
Let's first discuss the first option, which is "Manual status selections". This could be an option in the "Account Settings" menu, or as a dropdown menu on your own status. I prefer the second option, so here is what I think it should look like.

![image](https://cloud.githubusercontent.com/assets/18113170/25586716/80053950-2e98-11e7-84a2-fe9c39210f7c.png)

My first idea, which I like less, would look like the image below.

![image](https://cloud.githubusercontent.com/assets/18113170/25586918/8a0a5fd8-2e99-11e7-9022-382e698b80c6.png)

This second design, inspired by Tymoji ([forums](https://scratch.mit.edu/discuss/topic/197642/); [repo](https://github.com/Tymewalk/Tymoji)), has the following positive aspects

* We can add more settings later
* You can't accidentally change your status

but these negatives

* The Scratch Team might not like the fact that it is on the Account Settings page
* It is inconvenient for the user to get to

In any case, I think we should definitely implement this idea, regardless of how we do it.

**Comment by WorldLanguages** [comment]
I'd prefer to keep this (simple) setting on the profile. If we add more settings later, we should make a dedicated page for it.

**Comment by joker314** [comment]
Okay, I've been working on it for the last ~15 minutes it should be ready soon

**Comment by WorldLanguages** [comment]
I'll work on these today

**Comment by JordanB-1337** [comment]
nice close it to give us all a notification

**Comment by joker314** [comment]
It's because, @JordanB-1337 the issue is no longer relevant -- due to the past updates and such.


There isn't a way to close an issue without notifying :(
